### ISSUE TITLE
ObfuscationReflectionHelper should use SRG name only

### ISSUE THREAD

**Issue by 3TUSK** [OhTheDungeon/Vocation_Diary#2]
https://github.com/OhTheDungeon/Vocation_Diary/blob/b3e4bd033d0549ed63840ac3da3405e25f54087b/src/main/java/cn/shadow/vacation_diary/dimension/VocationDimension.java#L34-L35

the fact that you are using `delegate` rather than its SRG name `field_76115_a` is causing crash:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/24/20 2:40 PM
Description: Exception ticking world

net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: delegate
        at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:242) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:87) ~[?:?] {re:classloading}
        at cn.shadow.vacation_diary.dimension.VocationDimension.setWorldTime(VocationDimension.java:35) ~[?:1.0] {re:classloading}
        at net.minecraft.world.World.func_72877_b(World.java:1007) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217389_a(World.java:1013) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:311) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
Caused by: java.lang.NoSuchFieldException: delegate
        at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_252] {}
        at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:236) ~[?:?] {re:classloading}
        ... 10 more
```

**Comment by 3TUSK** [comment]
Fixed in https://github.com/OhTheDungeon/Vocation_Diary/commit/526f20656e665cbf4ee814a1995175929398c120
